export const availableIngredients = [
  "pimienta negra",
  "geranio",
  "cuero",
  "enebro de virginia",
  "pimienta rosa",
  "violeta",
  "bergamota",
  "manzana",
  "naranja",
  "cardamomo",
  "piña",
  "jengibre",
  "iris",
  "lavanda",
  "menta",
  "vainilla",
  "notas minerales",
  "sal",
  "hojas de violeta",
  "mandarina"
];